name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run main.py in MOCK mode (single turn)
        env:
          MOCK_MODE: "1"      # enable mocks (no audio/servers)
          MAX_TURNS: "1"      # finish quickly
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev
          python main.py --mock

